#pragma once

enum UID {
	ALIAS_TEXTBOX,
	USERNAME_TEXTBOX,
	PASSWORD_TEXTBOX,
	ADD_ACCOUNT_BUTTON,
	REMOVE_ACCOUNT_BUTTON,
	ACCOUNT_LISTBOX,
	LOGIN_BUTTON,
	DIALOG_ACCOUNT_INFO,
	DIALOG_YES_BUTTON,
	DIALOG_NO_BUTTON,
};